# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cee81f158391a230f3da7f7ca03fb15a3e9c6d18a53f3580f00af93bc984bbd3b8d9de9f345c020a05e33cf6050814c40488d830f03f2e28717b72513c11167

test:
  secret_key_base: 54028947fa0b40403fa382ddcafd5c9acea4027ae3de595ebe8fd12435388b4e906bc95ce2f37d376c67abe237ac31c6dac0315042315690629cf8f8bed8d0e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
